services:
  - type: web
    name: gestor-tareas-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
 